/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/App.jsx',
    './src/main.jsx',
    './index.html',
    "./src/*",
    "./src/components/*",
    "./src/pages/AllGames.jsx",
    "./src/pages/SelectCards.jsx",    
    "./src/pages/Al.jsx",    
    "./src/pages/TurnRouter.jsx",    
    "./src/pages/AllGames.jsx",    
    // "./",
    // "./",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      "yellow": "#FDCAA40",
      "lightYellow": "#FDD669",
      "blue": "#3772FF",
      "lightBlue": "#6492FF",
      "red": "#DF2935",
      "lightRed": "#E65962",
      "egg": "#E6E8E6",
      "lightEgg": "#ECEEEC",
      "blackish": "#080708",
      "lightBlackish": "#423A42",


      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
    },
    extend: {},
  },
  plugins: [],
}
