puts '🍪 Seeding...'

user0 = User.create(name: "Joe Biden", givenName: "Joey", familyName: "Biden", email: 'goebidemrecords@gmail.com', googleImageUrl: 'https://lh3.googleusercontent.com/a/AEdFTp46KHv6y1vpQO986BHr6nZzL8JGOwVvQcsEtMY=s96-c', googleId: '115686375380160512803', token: "tokentoken")

user1 = User.create(name: "Larson Collier", email: 'collier.larson@gmail.com', givenName: 'Larson', familyName: 'Collier', googleId: '106319424501130968820', googleImageUrl: 'https://lh3.googleusercontent.com/a/AEdFTp5a4dYww8NfYeiv-SWZgqL-L5GUeAT_E3GznpPWGAo=s96-c', token: "tokentoken")
user2 = User.create(name: "Katherine Tsai", email: 'katherine@gmail.com', googleImageUrl: 'https://wallpapers.com/images/featured/4co57dtwk64fb7lv.jpg', googleId: '1234', token: "tokentoken")
user3 = User.create(name: "Vincent Lee", email: 'vincent@gmail.com', googleImageUrl: 'https://wallpapers.com/images/featured/4co57dtwk64fb7lv.jpg', googleId: '1234', token: "tokentoken")
user4 = User.create(name: "Serrin Doscher", email: 'serrin@gmail.com', googleImageUrl: 'https://i.pinimg.com/736x/5a/e5/98/5ae598ff624217b9a5c008beb8c512d0.jpg', googleId: '1234', token: "tokentoken")


friendship0 = Friendship.create(p1Id: user1.id, p2Id: user0.id)
friendship1 = Friendship.create(p1Id: user1.id, p2Id: user2.id)
friendship2 = Friendship.create(p1Id: user3.id, p2Id: user4.id)
friendship3 = Friendship.create(p1Id: user1.id, p2Id: user3.id)
friendship4 = Friendship.create(p1Id: user1.id, p2Id: user4.id)

# cardset = CardSet.create(topicName: 'Food')
cardset1 = CardSet.create(topicName: 'Flat Iron Staff')
cardset2 = CardSet.create(topicName: 'Phase 5')

# card1 = Card.create(cardSetId: cardset.id, name: 'Brunswick Stew',image: 'backend/app/assets/images/food/white-brunswick stew.jpg' )
# card2 = Card.create(cardSetId: cardset.id, name: 'Burger',image: 'backend/app/assets/images/food/white-burger.jfif')
# Card.create(cardSetId: cardset.id, name: 'Cereal',image: 'backend/app/assets/images/food/white-cereal.jpeg')
# Card.create(cardSetId: cardset.id, name: 'Ceviche',image: 'backend/app/assets/images/food/white-ceviche.jpg')
# Card.create(cardSetId: cardset.id, name: 'Chicken',image: 'backend/app/assets/images/food/white-chicken.jpg')
# Card.create(cardSetId: cardset.id, name: 'Coleslaw',image: 'backend/app/assets/images/food/white-coleslaw.jpg')
# Card.create(cardSetId: cardset.id, name: 'Cornbread',image: 'backend/app/assets/images/food/white-cornbread.jpg')
# Card.create(cardSetId: cardset.id, name: 'Creme Brulee',image: 'backend/app/assets/images/food/white-creme brulee.png')
# Card.create(cardSetId: cardset.id, name: 'Donut',image: 'backend/app/assets/images/food/white-donuts.jpg')
# Card.create(cardSetId: cardset.id, name: 'Eclair',image: 'backend/app/assets/images/food/white-eclair.jpg')
# Card.create(cardSetId: cardset.id, name: 'Gumdrop',image: 'backend/app/assets/images/food/white-gumdrop.jpg')
# Card.create(cardSetId: cardset.id, name: 'Jambalaya',image: 'backend/app/assets/images/food/white-jambalaya.jpg')
# Card.create(cardSetId: cardset.id, name: 'Japache',image: 'backend/app/assets/images/food/white-japchae.jpg')
# Card.create(cardSetId: cardset.id, name: 'Lobster Bisque',image: 'backend/app/assets/images/food/white-lobster bisque.jpg')
# Card.create(cardSetId: cardset.id, name: 'Macaroon',image: 'backend/app/assets/images/food/white-macaroon.jpg')
# Card.create(cardSetId: cardset.id, name: 'Musubi',image: 'backend/app/assets/images/food/white-musubi.jpg')
# Card.create(cardSetId: cardset.id, name: 'Onion Rings',image: 'backend/app/assets/images/food/white-onion rings.jpg')
# Card.create(cardSetId: cardset.id, name: 'Pasta',image: 'backend/app/assets/images/food/white-pasta.jpeg')
# Card.create(cardSetId: cardset.id, name: 'Pho',image: 'backend/app/assets/images/food/white-pho.jpg')
# Card.create(cardSetId: cardset.id, name: 'Pickled Eggs',image: 'backend/app/assets/images/food/white-pickled eggs.jpg')

Card.create(cardSetId: cardset1.id, name: 'Alina',image: 'backend/app/assets/images/staff/alina pisarenko.jpg')
Card.create(cardSetId: cardset1.id, name: 'Ben',image: 'backend/app/assets/images/staff/Ben Cavins.jpg')
Card.create(cardSetId: cardset1.id, name: 'Charlie',image: 'backend/app/assets/images/staff/Charlie Kozey.jpg')
Card.create(cardSetId: cardset1.id, name: 'Chelsea',image: 'backend/app/assets/images/staff/chelsea green.png')
Card.create(cardSetId: cardset1.id, name: 'Chett',image: 'backend/app/assets/images/staff/chett tiller.png')
Card.create(cardSetId: cardset1.id, name: 'Dakota',image: 'backend/app/assets/images/staff/dakota martinez.jpg')
Card.create(cardSetId: cardset1.id, name: 'Jeryel',image: 'backend/app/assets/images/staff/Jeryel Blanco.jpg')
Card.create(cardSetId: cardset1.id, name: 'Kate',image: 'backend/app/assets/images/staff/Kate Wackerle.jpg')
Card.create(cardSetId: cardset1.id, name: 'Laura',image: 'backend/app/assets/images/staff/laura berge.png')
Card.create(cardSetId: cardset1.id, name: 'Louis',image: 'backend/app/assets/images/staff/Louis Michael Medina.jpg')
Card.create(cardSetId: cardset1.id, name: 'MikeGPT',image: 'backend/app/assets/images/staff/MikeGPT.png')
Card.create(cardSetId: cardset1.id, name: 'Mohamed',image: 'backend/app/assets/images/staff/Mohamed Muflahi.jpg')
Card.create(cardSetId: cardset1.id, name: 'Ricardo',image: 'backend/app/assets/images/staff/Ricardo Guerra.jpg')
Card.create(cardSetId: cardset1.id, name: 'Slack Admin',image: 'backend/app/assets/images/staff/Slack Admin.png')

Card.create(cardSetId: cardset2.id, name: 'Amneet',image: 'backend/app/assets/images/phase5/amneet.jpg')
Card.create(cardSetId: cardset2.id, name: 'Colter',image: 'backend/app/assets/images/phase5/colter.png')
Card.create(cardSetId: cardset2.id, name: 'Cooper',image: 'backend/app/assets/images/phase5/cooper.jpg')
Card.create(cardSetId: cardset2.id, name: 'Connor',image: 'backend/app/assets/images/phase5/connor.png')
Card.create(cardSetId: cardset2.id, name: 'Cristian',image: 'backend/app/assets/images/phase5/cristian.png')
Card.create(cardSetId: cardset2.id, name: 'Helen',image: 'backend/app/assets/images/phase5/helen.jpg')
Card.create(cardSetId: cardset2.id, name: 'John',image: 'backend/app/assets/images/phase5/john.jpg')
Card.create(cardSetId: cardset2.id, name: 'Katherine',image: 'backend/app/assets/images/phase5/katherine.jpg')
Card.create(cardSetId: cardset2.id, name: 'Larson',image: 'backend/app/assets/images/phase5/larson.jpg')
Card.create(cardSetId: cardset2.id, name: 'Ryan',image: 'backend/app/assets/images/phase5/ryan.jpg')
Card.create(cardSetId: cardset2.id, name: 'Salman',image: 'backend/app/assets/images/phase5/salman.jpg')
Card.create(cardSetId: cardset2.id, name: 'Serrin',image: 'backend/app/assets/images/phase5/serrin.png')
Card.create(cardSetId: cardset2.id, name: 'Shivani',image: 'backend/app/assets/images/phase5/shivani.jpg')
Card.create(cardSetId: cardset2.id, name: 'Trevor',image: 'backend/app/assets/images/phase5/trevor.jpg')
Card.create(cardSetId: cardset2.id, name: 'Vincent',image: 'backend/app/assets/images/phase5/vincent.png')
Card.create(cardSetId: cardset2.id, name: 'Zaid',image: 'backend/app/assets/images/phase5/zaid.jpg')

# game1=Game.create(p1: user1.id, p2: user2.id, p1SecretCard: card1, p2SecretCard: card2)

puts '🍪 Done seeding!'